### ISSUE TITLE
[Release] v0.19.1

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#3059]
Right now, the `develop` branch of dbt:
- offers a significantly faster startup time vs. v0.19.0
- cannot be installed from `setup.py` alone

Let's get this into people's hands!

### Beta (v0.19.1b1)

- [x] **hologram**: Cut a new release that includes https://github.com/fishtown-analytics/hologram/pull/41. Upgrade (re-add) the `hologram` dependency in `setup.py`.
- [x] **dbt-mashumaro:** Can we pin a `git+` dependency to a GitHub tag and get `pip install dbt==0.19.1b1` to work, even if `dbt-mashumaro` is missing from PyPi? If so, let's create a stable GitHub tag from https://github.com/fishtown-analytics/dbt-mashumaro/commit/c25ed077e7982e2bfe8aee7df80bfeac63d3927f, and add the `git+` dependency to `setup.py`. If not, then we'll need to put `dbt-mashumaro` on PyPi.
- [x] Release v0.19.1b1 to PyPi. If Docker or Homebrew prove difficult (given the `git+` dependency), we can punt on them for now.

#### Mashumaro: https://github.com/fishtown-analytics/dbt/pull/3138
- [x] Incorporate the addition of `Union` types in `mashumaro==1.24`
- [x] Determine what we need from https://github.com/Fatal1ty/mashumaro/issues/32
- [x] Figure out if there are any other missing pieces. Ideally we don't need our fork at all :)

#### Rest of [v0.19.1 milestone](https://github.com/fishtown-analytics/dbt/milestone/63)
- [x] **Regression:** Ephemeral-of-ephemeral compiled SQL (#3056)
- [x] **Regression:** BigQuery dynamic `insert_overwrite` (#3063, #3095)
- [x] **Regression:** BigQuery scopes for service account + `gcloud` oauth (#3040)
- [x] **Misc:** Add tracking for resource counts (#3050)

#### dbt-release
- [x] Fix [Homebrew build](https://github.com/fishtown-analytics/dbt-release/runs/2098367664) relating to [v0.19.1 release](https://github.com/fishtown-analytics/dbt-release/runs/2098367664)

**Comment by kwigley** [comment]
Thanks for the detailed steps here ! @jtcohen6
