### ISSUE TITLE
Release v0.20.0 RC1

### ISSUE THREAD

**Issue by leahwicz** [fishtown-analytics/dbt#3388]
This is a checklist of what we need to do to release v0.20.0 RC1 

- [ ] [User-supplied fail_calc for tests](https://github.com/fishtown-analytics/dbt/issues/3321)
- [ ] [Add list RPC method](https://github.com/fishtown-analytics/dbt/issues/3311)
- [ ] [Add keys to list output, parametrize](https://github.com/fishtown-analytics/dbt/issues/3356)
- [ ] TODO: @kwigley can you add what else we need here please?

**Comment by leahwicz** [comment]
Closing as duplicate to:
https://github.com/fishtown-analytics/dbt/issues/3333
