### ISSUE TITLE
[Tracking] v0.20.0rc1 release

### ISSUE THREAD

**Issue by leahwicz** [fishtown-analytics/dbt#3439]
### Engineering TODOs:
- [x] Merge #3432 (nice last-minute work here Gerda)
- [x] dbt-release workflow [Leah + Kyle]
- [x] Create new protected branch 0.20.latest
- [x] [Add 0.19.2rc2 + 0.20.0rc1 to dbt Cloud](https://github.com/fishtown-analytics/dbt-cloud/pull/3124)
- [x] [Generate v2 schemas for manifest + run_results, push to schemas.getdbt.com](https://github.com/fishtown-analytics/dbt/issues/3393)
- [x] Bump plugin versions (dbt-spark + dbt-presto), add compatibility as needed
   - [x]  Spark - @gshank
       - https://github.com/fishtown-analytics/dbt-spark/issues/173
       - https://github.com/fishtown-analytics/dbt-spark/issues/175
       - https://github.com/fishtown-analytics/dbt-spark/issues/174
       - https://github.com/fishtown-analytics/dbt-spark/issues/176
   - [x]  Presto - @iknox-fa 
       - https://github.com/fishtown-analytics/dbt-presto/issues/42
       - https://github.com/fishtown-analytics/dbt-presto/issues/45
       - https://github.com/fishtown-analytics/dbt-presto/issues/43
       - https://github.com/fishtown-analytics/dbt-presto/issues/44
- [x] Add new dbt-spark versions to dbt Cloud as well (I don't want this to block getting core + other plugins in earlier)
   * @kwigley to create an issue in the platform repo to have them do the update

### Product TODOs:
- [x] Merge PRs into next.docs.getdbt.com
- [x] Release new minor version of dbt-utils with 0.20.0 compatibility
- [x] Publish discourse (draft here)
- [x] Announce in dbt Slack
