### ISSUE TITLE
automated testing for anonymized event tracking

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#833]
- [x] test actual == expected
- [x] either stub out http calls, or go full end-to-end and test the events that show up in Redshift

**Comment by cmcarthur** [comment]
https://github.com/fishtown-analytics/dbt/compare/tests/snowplow-tracking?expand=1

- [ ] profile is misconfigured 
- [ ] compilation failure
- [ ] archive
- [ ] catalog generate

**Comment by drewbanin** [comment]
This was merged in https://github.com/fishtown-analytics/dbt/pull/853
